	modLoader="javafml"
	loaderVersion="[31,)"
	license="MIT"
	
[[mods]]
	modId="armorhotswap"
	version="1.6"
	displayName="Armor Hotswap"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-hotswap"
	issueTrackerURL=""
	logoFile="ArmorHotswapLogo.png"
	credits=""
	authors="AreUThreateningMe"
	description='''
Right click while holding a piece of armor to swap it with the currently equipped armor'''

[[dependencies.armorhotswap]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.armorhotswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"
